use std::fmt::Debug;

use crate::{
    bit_board,
    piece::{self, DIR_EAST, DIR_NORTH, DIR_OFFSETS, DIR_SOUTH, DIR_WEST, TO_EDGE_OFFSETS},
    square::{BoardPos, Square},
    Color, Piece,
};

pub trait Move: Debug {
    fn src_idx(&self) -> i8;
    fn dst_idx(&self) -> i8;
}

pub type MoveByIdx = (usize, usize);
pub type MoveBySquare = (Square, Square);

impl Move for MoveByIdx {
    fn src_idx(&self) -> i8 {
        self.0 as i8
    }

    fn dst_idx(&self) -> i8 {
        self.1 as i8
    }
}

impl Move for MoveBySquare {
    fn src_idx(&self) -> i8 {
        self.0.into()
    }

    fn dst_idx(&self) -> i8 {
        self.1.into()
    }
}

// TODO: Consider refactoring to use `i8` everywhere and save a bunch of casting.

#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Board {
    pub black_bishops: u64,
    pub black_king: u64,
    pub black_knights: u64,
    pub black_pawns: u64,
    pub black_queens: u64,
    pub black_rooks: u64,
    pub can_black_castle_king_side: bool,
    pub can_black_castle_queen_side: bool,
    pub can_white_castle_king_side: bool,
    pub can_white_castle_queen_side: bool,
    pub en_passant_target_idx: Option<usize>,
    pub is_whites_turn: bool,
    #[deprecated(note = "in the future the `en_passant_target_idx` should be used")]
    pub piece_eligible_for_en_passant: Vec<(usize, usize)>,
    pub promote_idx: Option<usize>,
    pub white_bishops: u64,
    pub white_king: u64,
    pub white_knights: u64,
    pub white_pawns: u64,
    pub white_queens: u64,
    pub white_rooks: u64,
}

impl Board {
    pub const HEIGHT: usize = 8;
    pub const WIDTH: usize = 8;
    pub const SIZE: usize = Self::HEIGHT * Self::WIDTH;

    fn check_and_add_en_passant_eligibility(
        &mut self,
        src_ins: &PieceInstance,
        src_idx: usize,
        hit_idx: usize,
    ) {
        if src_ins.piece != Piece::Pawn {
            return;
        }

        let src_y = src_idx / Self::WIDTH;
        let hit_y = hit_idx / Self::WIDTH;

        let move_could_result_in_en_passant = src_y.abs_diff(hit_y) == 2;
        if !move_could_result_in_en_passant {
            return;
        }

        for hit_pos in [
            (hit_idx as i8 + DIR_OFFSETS[DIR_WEST]) as usize,
            (hit_idx as i8 + DIR_OFFSETS[DIR_EAST]) as usize,
        ] {
            if let Some(ins) = self.get(&hit_pos) {
                if ins.color != src_ins.color {
                    self.piece_eligible_for_en_passant.push((hit_pos, hit_idx));
                }
            }
        }
    }

    fn check_and_execute_castle(
        &mut self,
        src_ins: &PieceInstance,
        src_idx: usize,
        hit_idx: usize,
    ) {
        if !matches!(src_ins.piece, Piece::King) {
            return;
        }

        if src_idx.abs_diff(hit_idx) != 2 {
            return;
        }

        let king_move_dir = match src_idx as i8 - hit_idx as i8 > 0 {
            true => DIR_WEST,
            false => DIR_EAST,
        };

        let rook_src_idx = (src_idx as i8
            + (TO_EDGE_OFFSETS[src_idx][king_move_dir] as i8) * DIR_OFFSETS[king_move_dir])
            as usize;
        let rook_ins = self.get(&rook_src_idx);
        let rook_des_idx = (hit_idx as i8 - DIR_OFFSETS[king_move_dir]) as usize;

        self.set_by_idx(rook_src_idx, None);
        self.set_by_idx(rook_des_idx, rook_ins);
    }

    fn check_and_execute_en_passant(&mut self, src_ins: &PieceInstance, hit_idx: usize) {
        if matches!(src_ins.piece, Piece::Pawn) && matches!(self.get(&hit_idx), None) {
            let idx_behind_hit =
                ((hit_idx as i8) - DIR_OFFSETS[Self::get_attack_dir_of(&src_ins.color)]) as usize;

            self.set_by_idx(idx_behind_hit, None);
        }
    }

    /// Execute a move.
    /// Notably this does not check the move's validity, (if you want to do that use
    /// [`Piece::is_valid_move()`]). **However**, this function needs to check if
    /// given move is a special one (en passant or castle). So calling with invalid
    /// moves might result in severe side effects and crash the program.
    /// As an API consumer, it is advisable to only call with moves generated by
    /// [`Piece::get_moves_for_piece_at()`].
    ///
    /// # Panics
    /// If no piece is at the source index.
    pub fn do_move(&mut self, mv: &dyn Move) {
        let src_idx = mv.src_idx();
        let dst_idx = mv.dst_idx();

        let src_ins = match self.get(&src_idx) {
            Some(i) => i,
            None => panic!(
                "cannot execute move '{:?}' because there is no piece at the source index",
                mv
            ),
        };

        self.remove_old_en_passant_moves();
        // Adds en passant moves for the next turn
        self.check_and_add_en_passant_eligibility(&src_ins, src_idx as usize, dst_idx as usize);
        // Execute en passant moves for this turn
        self.check_and_execute_en_passant(&src_ins, dst_idx as usize);

        if src_ins.piece == Piece::King {
            match src_ins.color {
                Color::Black => {
                    self.can_black_castle_king_side = false;
                    self.can_black_castle_queen_side = false;
                }
                Color::White => {
                    self.can_white_castle_king_side = false;
                    self.can_white_castle_queen_side = false;
                }
            }
        }

        if src_ins.piece == Piece::Rook {
            match (&src_ins.color, src_idx) {
                (Color::Black, 0) => self.can_black_castle_queen_side = false,
                (Color::Black, 7) => self.can_black_castle_king_side = false,
                (Color::White, 56) => self.can_white_castle_queen_side = false,
                (Color::White, 63) => self.can_white_castle_king_side = false,
                _ => (),
            }
        }

        self.check_and_execute_castle(&src_ins, src_idx as usize, dst_idx as usize);
        self.set_by_idx(src_idx as usize, None);
        self.set_by_idx(dst_idx as usize, Some(src_ins));
    }

    pub fn get(&self, idx: &dyn BoardPos) -> Option<PieceInstance> {
        let i = idx.idx() as u64;

        if bit_board::is_set(self.black_bishops, i) {
            return Some(PieceInstance::new(Color::Black, Piece::Bishop));
        }
        if bit_board::is_set(self.black_king, i) {
            return Some(PieceInstance::new(Color::Black, Piece::King));
        }
        if bit_board::is_set(self.black_knights, i) {
            return Some(PieceInstance::new(Color::Black, Piece::Knight));
        }
        if bit_board::is_set(self.black_pawns, i) {
            return Some(PieceInstance::new(Color::Black, Piece::Pawn));
        }
        if bit_board::is_set(self.black_queens, i) {
            return Some(PieceInstance::new(Color::Black, Piece::Queen));
        }
        if bit_board::is_set(self.black_rooks, i) {
            return Some(PieceInstance::new(Color::Black, Piece::Rook));
        }

        if bit_board::is_set(self.white_bishops, i) {
            return Some(PieceInstance::new(Color::White, Piece::Bishop));
        }
        if bit_board::is_set(self.white_king, i) {
            return Some(PieceInstance::new(Color::White, Piece::King));
        }
        if bit_board::is_set(self.white_knights, i) {
            return Some(PieceInstance::new(Color::White, Piece::Knight));
        }
        if bit_board::is_set(self.white_pawns, i) {
            return Some(PieceInstance::new(Color::White, Piece::Pawn));
        }
        if bit_board::is_set(self.white_queens, i) {
            return Some(PieceInstance::new(Color::White, Piece::Queen));
        }
        if bit_board::is_set(self.white_rooks, i) {
            return Some(PieceInstance::new(Color::White, Piece::Rook));
        }

        None
    }

    /// Get the direction ([`DIR_NORTH`]/[`DIR_SOUTH`]) in which the pieces are
    /// attacking. Basically the opposite side of where the pieces started.
    pub fn get_attack_dir_of(color: &Color) -> usize {
        match color {
            Color::Black => DIR_SOUTH,
            Color::White => DIR_NORTH,
        }
    }

    pub fn is_pos_attacked_by(&self, pos: &dyn BoardPos, atk_color: &Color) -> bool {
        // Since the attacks are essentially mirrored for both sides, we just generate
        // the opponent attacks on the square to check. If the attack includes the
        // position if our piece, we can be attacked, and the reverse is also true.
        //
        // Let's say we want to see if a white pawn on E5 can attack the square D6:
        //
        // 8   . . . . . . . .
        // 7   . . . . . . . .
        // 6   . . . . . . . .
        // 5   . . . . 1 . . .
        // 4   . . . . . . . .
        // 3   . . . . . . . .
        // 2   . . . . . . . .
        // 1   . . . . . . . .
        //
        //     a b c d e f g h
        //
        // We now simply lookup the attacks of the **opponent** on the position we
        // want to check (pawn attacks of the square D6):
        //
        // 8   . . . . . . . .
        // 7   . . . . . . . .
        // 6   . . . . . . . .
        // 5   . . 1 . 1 . . .
        // 4   . . . . . . . .
        // 3   . . . . . . . .
        // 2   . . . . . . . .
        // 1   . . . . . . . .
        //
        //     a b c d e f g h
        //
        // We can see that the bit on E5 is set on both boards, thus the square
        // D6 can be attacked by the white pawn on E5.

        let all_pieces = self.black_bishops
            | self.black_king
            | self.black_knights
            | self.black_pawns
            | self.black_queens
            | self.black_rooks
            | self.white_bishops
            | self.white_king
            | self.white_knights
            | self.white_pawns
            | self.white_queens
            | self.white_rooks;

        if atk_color == &Color::White {
            if bit_board::has_set_bits(
                piece::get_bishop_attacks_for(pos, all_pieces) & self.white_bishops,
            ) {
                return true;
            }
        } else {
            if bit_board::has_set_bits(
                piece::get_bishop_attacks_for(pos, all_pieces) & self.black_bishops,
            ) {
                return true;
            }
        }

        if atk_color == &Color::White {
            if bit_board::has_set_bits(piece::KNIGHT_ATTACKS[pos] & self.white_knights) {
                return true;
            }
        } else {
            if bit_board::has_set_bits(piece::KNIGHT_ATTACKS[pos] & self.black_knights) {
                return true;
            }
        }

        if atk_color == &Color::White {
            if bit_board::has_set_bits(piece::KING_ATTACKS[pos] & self.white_king) {
                return true;
            }
        } else {
            if bit_board::has_set_bits(piece::KING_ATTACKS[pos] & self.black_king) {
                return true;
            }
        }

        // TODO: if there was a function to get the "opposing pawns", this could
        // be simplified to:
        // ```
        // let opposing = atk_color.opposing();
        // if bit_board::has_set_bits(piece::PAWN_ATTACKS[opposing][pos] & self.get_pawns(opposing)) {
        //     return true;
        // }
        // ```
        // alternatively just do:
        // ```
        // let opposing_pawns = if atk_color == Color::White { self.black_pawns } else { self.white_pawns };
        // ```
        // The different boards could also just be stored in an table. E.g.: `self.pawns[Color::Black]`.
        if atk_color == &Color::White {
            if bit_board::has_set_bits(piece::PAWN_ATTACKS[Color::Black][pos] & self.white_pawns) {
                return true;
            }
        } else {
            if bit_board::has_set_bits(piece::PAWN_ATTACKS[Color::White][pos] & self.black_pawns) {
                return true;
            }
        }

        // The Queen attacks are already covered by checking bishops and rooks,
        // and not explicitly checked here.

        if atk_color == &Color::White {
            if bit_board::has_set_bits(
                piece::get_rook_attacks_for(pos, all_pieces) & self.white_rooks,
            ) {
                return true;
            }
        } else {
            if bit_board::has_set_bits(
                piece::get_rook_attacks_for(pos, all_pieces) & self.black_rooks,
            ) {
                return true;
            }
        }

        false
    }

    pub fn new_empty() -> Self {
        Self {
            black_bishops: 0,
            black_king: 0,
            black_knights: 0,
            black_pawns: 0,
            black_queens: 0,
            black_rooks: 0,
            can_black_castle_king_side: false,
            can_black_castle_queen_side: false,
            can_white_castle_king_side: false,
            can_white_castle_queen_side: false,
            en_passant_target_idx: None,
            is_whites_turn: true,
            piece_eligible_for_en_passant: Vec::with_capacity(2),
            promote_idx: None,
            white_bishops: 0,
            white_king: 0,
            white_knights: 0,
            white_pawns: 0,
            white_queens: 0,
            white_rooks: 0,
        }
    }

    pub fn new_with_standard_formation() -> Self {
        let mut board = Self::new_empty();

        board.can_black_castle_king_side = true;
        board.can_black_castle_queen_side = true;
        board.can_white_castle_king_side = true;
        board.can_white_castle_queen_side = true;

        // Standard chess formation:
        board.set_by_idx(0, Some(PieceInstance::new(Color::Black, Piece::Rook)));
        board.set_by_idx(1, Some(PieceInstance::new(Color::Black, Piece::Knight)));
        board.set_by_idx(2, Some(PieceInstance::new(Color::Black, Piece::Bishop)));
        board.set_by_idx(3, Some(PieceInstance::new(Color::Black, Piece::Queen)));
        board.set_by_idx(4, Some(PieceInstance::new(Color::Black, Piece::King)));
        board.set_by_idx(5, Some(PieceInstance::new(Color::Black, Piece::Bishop)));
        board.set_by_idx(6, Some(PieceInstance::new(Color::Black, Piece::Knight)));
        board.set_by_idx(7, Some(PieceInstance::new(Color::Black, Piece::Rook)));

        board.set_by_idx(8, Some(PieceInstance::new(Color::Black, Piece::Pawn)));
        board.set_by_idx(9, Some(PieceInstance::new(Color::Black, Piece::Pawn)));
        board.set_by_idx(10, Some(PieceInstance::new(Color::Black, Piece::Pawn)));
        board.set_by_idx(11, Some(PieceInstance::new(Color::Black, Piece::Pawn)));
        board.set_by_idx(12, Some(PieceInstance::new(Color::Black, Piece::Pawn)));
        board.set_by_idx(13, Some(PieceInstance::new(Color::Black, Piece::Pawn)));
        board.set_by_idx(14, Some(PieceInstance::new(Color::Black, Piece::Pawn)));
        board.set_by_idx(15, Some(PieceInstance::new(Color::Black, Piece::Pawn)));

        board.set_by_idx(48, Some(PieceInstance::new(Color::White, Piece::Pawn)));
        board.set_by_idx(49, Some(PieceInstance::new(Color::White, Piece::Pawn)));
        board.set_by_idx(50, Some(PieceInstance::new(Color::White, Piece::Pawn)));
        board.set_by_idx(51, Some(PieceInstance::new(Color::White, Piece::Pawn)));
        board.set_by_idx(52, Some(PieceInstance::new(Color::White, Piece::Pawn)));
        board.set_by_idx(53, Some(PieceInstance::new(Color::White, Piece::Pawn)));
        board.set_by_idx(54, Some(PieceInstance::new(Color::White, Piece::Pawn)));
        board.set_by_idx(55, Some(PieceInstance::new(Color::White, Piece::Pawn)));

        board.set_by_idx(56, Some(PieceInstance::new(Color::White, Piece::Rook)));
        board.set_by_idx(57, Some(PieceInstance::new(Color::White, Piece::Knight)));
        board.set_by_idx(58, Some(PieceInstance::new(Color::White, Piece::Bishop)));
        board.set_by_idx(59, Some(PieceInstance::new(Color::White, Piece::Queen)));
        board.set_by_idx(60, Some(PieceInstance::new(Color::White, Piece::King)));
        board.set_by_idx(61, Some(PieceInstance::new(Color::White, Piece::Bishop)));
        board.set_by_idx(62, Some(PieceInstance::new(Color::White, Piece::Knight)));
        board.set_by_idx(63, Some(PieceInstance::new(Color::White, Piece::Rook)));

        board
    }

    /// Fullfil the outstanding promotion.
    ///
    /// Promote a pawn that has reached the end of the board to the specified piece.
    /// Possibilities to promote to are:
    /// - [`Piece::Bishop`]
    /// - [`Piece::Knight`]
    /// - [`Piece::Queen`]
    /// - [`Piece::Rook`]
    pub fn promote_piece_to(&mut self, promote_to: Piece) {
        assert!(
            matches!(
                promote_to,
                Piece::Bishop | Piece::Knight | Piece::Queen | Piece::Rook,
            ),
            "pawn cannot be promoted to '{:?}'",
            promote_to
        );

        let idx = self
            .promote_idx
            .expect("cannot promote as no outstanding promotion was detected");

        let ins = match self.get(&idx) {
            Some(i) => i.clone(),
            None => panic!("no piece to promote at '{}'", idx),
        };

        assert!(
            matches!(ins.piece, Piece::Pawn),
            "can only promote pawns but piece ('{}') was '{:?}'",
            idx,
            ins.piece,
        );

        self.set_by_idx(idx, Some(PieceInstance::new(ins.color, promote_to)));

        self.promote_idx = None
    }

    fn remove_old_en_passant_moves(&mut self) {
        self.piece_eligible_for_en_passant.clear()
    }

    pub fn set(&mut self, idx: &dyn BoardPos, color: Color, piece: Piece) {
        self.set_by_idx(idx.idx() as usize, Some(PieceInstance::new(color, piece)));
    }

    #[deprecated(note = "simply use `set` instead")]
    pub fn set_by_idx(&mut self, idx: usize, pos: Option<PieceInstance>) {
        // self.poses[idx] = pos;

        if let Some(ins) = pos.as_ref() {
            let i = idx as u64;

            match (&ins.color, &ins.piece) {
                (Color::Black, Piece::Bishop) => bit_board::set_bit(&mut self.black_bishops, i),
                (Color::Black, Piece::King) => bit_board::set_bit(&mut self.black_king, i),
                (Color::Black, Piece::Knight) => bit_board::set_bit(&mut self.black_knights, i),
                (Color::Black, Piece::Pawn) => bit_board::set_bit(&mut self.black_pawns, i),
                (Color::Black, Piece::Queen) => bit_board::set_bit(&mut self.black_queens, i),
                (Color::Black, Piece::Rook) => bit_board::set_bit(&mut self.black_rooks, i),
                (Color::White, Piece::Bishop) => bit_board::set_bit(&mut self.white_bishops, i),
                (Color::White, Piece::King) => bit_board::set_bit(&mut self.white_king, i),
                (Color::White, Piece::Knight) => bit_board::set_bit(&mut self.white_knights, i),
                (Color::White, Piece::Pawn) => bit_board::set_bit(&mut self.white_pawns, i),
                (Color::White, Piece::Queen) => bit_board::set_bit(&mut self.white_queens, i),
                (Color::White, Piece::Rook) => bit_board::set_bit(&mut self.white_rooks, i),
            }
        } else {
            let i = idx as u64;

            bit_board::clear_bit(&mut self.black_bishops, i);
            bit_board::clear_bit(&mut self.black_king, i);
            bit_board::clear_bit(&mut self.black_knights, i);
            bit_board::clear_bit(&mut self.black_pawns, i);
            bit_board::clear_bit(&mut self.black_queens, i);
            bit_board::clear_bit(&mut self.black_rooks, i);

            bit_board::clear_bit(&mut self.white_bishops, i);
            bit_board::clear_bit(&mut self.white_bishops, i);
            bit_board::clear_bit(&mut self.white_king, i);
            bit_board::clear_bit(&mut self.white_knights, i);
            bit_board::clear_bit(&mut self.white_pawns, i);
            bit_board::clear_bit(&mut self.white_queens, i);
            bit_board::clear_bit(&mut self.white_rooks, i);
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PieceInstance {
    pub color: Color,
    pub piece: Piece,
}

impl PieceInstance {
    pub fn new(color: Color, piece: Piece) -> Self {
        Self { piece, color }
    }
}

#[cfg(test)]
mod tests {
    use crate::bit_board::U64PerSquare;

    use super::*;

    use Square::*;

    #[test]
    fn is_pos_attacked_not_attacked() {
        let board = Board::new_empty();

        assert_eq!(board.is_pos_attacked_by(&A8, &Color::Black), false);
        assert_eq!(board.is_pos_attacked_by(&A8, &Color::White), false);
    }

    #[test]
    fn is_pos_attacked_by_bishop_no_blockers() {
        for color in [Color::Black, Color::White] {
            let mut board = Board::new_empty();
            board.set(&F4, color.clone(), Piece::Bishop);

            for pos in [B8, C7, D6, E5, H6, G5, E3, D2, C1, G3, H2] {
                assert_eq!(board.is_pos_attacked_by(&pos, &color), true, "{:?}", &color);
            }
        }
    }

    #[test]
    fn is_pos_attacked_by_bishop_blockers() {
        const ALL_SQUARES_BEHIND: [Square; 3] = [E6, F7, G8];

        for atk_color in &[Color::Black, Color::White] {
            let mut board = Board::new_empty();
            board.set(&B3, atk_color.clone(), Piece::Bishop);

            let var_name: &[(Color, Piece, &[Square])] = &[
                // Opposing blocking pieces
                (atk_color.opposing(), Piece::Bishop, &ALL_SQUARES_BEHIND),
                (atk_color.opposing(), Piece::King, &ALL_SQUARES_BEHIND),
                (atk_color.opposing(), Piece::Knight, &ALL_SQUARES_BEHIND),
                (atk_color.opposing(), Piece::Pawn, &ALL_SQUARES_BEHIND),
                (atk_color.opposing(), Piece::Queen, &ALL_SQUARES_BEHIND),
                (atk_color.opposing(), Piece::Rook, &ALL_SQUARES_BEHIND),
                // It's a bit more tricky for friendly blocking pieces, since they
                // may attack themselves.
                (*atk_color, Piece::Bishop, &[]),
                (*atk_color, Piece::King, &[F7, G8]),
                (*atk_color, Piece::Knight, &ALL_SQUARES_BEHIND),
                (*atk_color, Piece::Pawn, &[F7, G8]),
                (*atk_color, Piece::Queen, &[]),
                (*atk_color, Piece::Rook, &ALL_SQUARES_BEHIND),
            ];
            for (blocking_color, blocking_piece, blocked_squares) in var_name {
                let mut board = board.clone();
                board.set(&D5, *blocking_color, *blocking_piece);

                for pos in *blocked_squares {
                    assert_eq!(
                        board.is_pos_attacked_by(pos, &atk_color),
                        false,
                        "attacking: {:?}, blocking: {:?} {:?}",
                        atk_color,
                        atk_color,
                        blocking_piece
                    );
                }
            }
        }
    }

    #[test]
    fn is_pos_attacked_by_king() {
        for color in [Color::Black, Color::White] {
            let mut board = Board::new_empty();
            board.set(&F7, color.clone(), Piece::King);

            for pos in [E8, F8, G8, E7, G7, E6, F6, G6] {
                assert_eq!(board.is_pos_attacked_by(&pos, &color), true, "{:?}", &color);
            }
        }
    }

    #[test]
    fn is_pos_attacked_by_knight() {
        for color in [Color::Black, Color::White] {
            let mut board = Board::new_empty();
            board.set(&B4, color.clone(), Piece::Knight);

            for pos in [A6, C6, D5, D3, C2, A2] {
                assert_eq!(board.is_pos_attacked_by(&pos, &color), true, "{:?}", &color);
            }
        }
    }

    #[test]
    fn is_pos_attacked_attacked_by_white_pawn() {
        let mut board = Board::new_empty();
        board.set(&E5, Color::White, Piece::Pawn);

        assert_eq!(board.is_pos_attacked_by(&D6, &Color::White), true);
        assert_eq!(board.is_pos_attacked_by(&F6, &Color::White), true);
    }

    #[test]
    fn is_pos_attacked_by_black_pawn() {
        let mut board = Board::new_empty();
        board.set(&C6, Color::Black, Piece::Pawn);

        assert_eq!(board.is_pos_attacked_by(&B5, &Color::Black), true);
        assert_eq!(board.is_pos_attacked_by(&D5, &Color::Black), true);
    }

    // The queen checks are covered by the bishop and rook checks.
    // So they are not checked explicitly here.

    #[test]
    fn is_pos_attacked_by_rook_no_blockers() {
        for color in [Color::Black, Color::White] {
            let mut board = Board::new_empty();
            board.set(&G7, color.clone(), Piece::Rook);

            for pos in [A7, B7, C7, D7, E7, F7, H7, G8, G6, G5, G4, G3, G2, G1] {
                assert_eq!(board.is_pos_attacked_by(&pos, &color), true, "{:?}", &color);
            }
        }
    }

    #[test]
    fn is_pos_attacked_by_white_rook() {
        const ALL_SQUARES_BEHIND: [Square; 4] = [D5, D6, D7, D8];

        for atk_color in &[Color::Black, Color::White] {
            let mut board = Board::new_empty();
            board.set(&D2, atk_color.clone(), Piece::Rook);

            let var_name: &[(Color, Piece, &[Square])] = &[
                // Opposing blocking pieces
                (atk_color.opposing(), Piece::Bishop, &ALL_SQUARES_BEHIND),
                (atk_color.opposing(), Piece::King, &ALL_SQUARES_BEHIND),
                (atk_color.opposing(), Piece::Knight, &ALL_SQUARES_BEHIND),
                (atk_color.opposing(), Piece::Pawn, &ALL_SQUARES_BEHIND),
                (atk_color.opposing(), Piece::Queen, &ALL_SQUARES_BEHIND),
                (atk_color.opposing(), Piece::Rook, &ALL_SQUARES_BEHIND),
                // It's a bit more tricky for friendly blocking pieces, since they
                // may attack themselves.
                (*atk_color, Piece::Bishop, &ALL_SQUARES_BEHIND),
                (*atk_color, Piece::King, &[D6, D7, D8]),
                (*atk_color, Piece::Knight, &ALL_SQUARES_BEHIND),
                (*atk_color, Piece::Pawn, &ALL_SQUARES_BEHIND),
                (*atk_color, Piece::Queen, &[]),
                (*atk_color, Piece::Rook, &[]),
            ];
            for (blocking_color, blocking_piece, blocked_squares) in var_name {
                let mut board = board.clone();
                board.set(&D4, *blocking_color, *blocking_piece);

                for pos in *blocked_squares {
                    assert_eq!(
                        board.is_pos_attacked_by(pos, &atk_color),
                        false,
                        "attacking: {:?}, blocking: {:?} {:?}",
                        atk_color,
                        atk_color,
                        blocking_piece
                    );
                }
            }
        }
    }

    // TODO: move or remove pre bit board stuff
    // pre bit board stuff below

    #[test]
    fn en_passant_removes_the_other_piece_you() {
        let mut board = board();
        board.set_by_idx(8, ins_black(Piece::Pawn));
        board.set_by_idx(25, ins_white(Piece::Pawn));

        board.do_move(&(8, 24));
        board.do_move(&(25, 16));

        assert!(
            matches!(board.get(&Square::A5), None),
            "piece was not removed {}",
            board
        );
    }

    #[test]
    fn en_passant_removes_the_other_piece_opponent() {
        let mut board = board();
        board.set_by_idx(33, ins_black(Piece::Pawn));
        board.set_by_idx(48, ins_white(Piece::Pawn));

        board.do_move(&(48, 32));
        board.do_move(&(33, 40));

        assert!(
            matches!(board.get(&Square::A4), None),
            "piece was not removed {}",
            board
        );
    }

    #[test]
    fn en_passant_is_not_done_for_other_pieces() {
        let mut board = board();
        board.set_by_idx(33, ins_black(Piece::Bishop));
        board.set_by_idx(32, ins_white(Piece::Pawn));

        board.do_move(&(33, 40));

        assert!(
            !matches!(board.get(&Square::A4), None),
            "piece was removed {}",
            board
        );
    }

    #[test]
    fn en_passant_is_not_executed_on_normal_take() {
        let mut board = board();
        board.set_by_idx(33, ins_white(Piece::Pawn));
        board.set_by_idx(34, ins_black(Piece::Pawn));
        board.set_by_idx(41, ins_white(Piece::Pawn));

        board.do_move(&(34, 41));

        assert!(
            !matches!(board.get(&Square::B4), None),
            "piece was removed {}",
            board
        );
    }

    #[test]
    fn castle_moves_the_rook_you_west() {
        let mut board = board_castle_you_west();

        board.do_move(&(60, 58));

        assert_eq!(
            board.get(&Square::A1).as_ref(),
            None,
            "rook was not removed {}",
            board,
        );

        assert_eq!(
            board.get(&Square::D1).as_ref(),
            ins_white(Piece::Rook).as_ref(),
            "rook was not moved {}",
            board
        );
    }

    #[test]
    fn castle_moves_the_rook_you_east() {
        let mut board = board_castle_you_east();

        board.do_move(&(60, 62));

        assert_eq!(
            board.get(&Square::H1).as_ref(),
            None,
            "rook was not removed {}",
            board,
        );

        assert_eq!(
            board.get(&Square::F1).as_ref(),
            ins_white(Piece::Rook).as_ref(),
            "rook was not moved {}",
            board,
        );
    }

    #[test]
    fn castle_moves_the_rook_opponent_west() {
        let mut board = board();
        board.set_by_idx(0, ins_black(Piece::Rook));
        board.set_by_idx(4, ins_black(Piece::King));

        board.do_move(&(4, 2));

        assert_eq!(
            board.get(&Square::A8).as_ref(),
            None,
            "rook was not removed {}",
            board,
        );

        assert_eq!(
            board.get(&Square::D8).as_ref(),
            ins_black(Piece::Rook).as_ref(),
            "rook was not moved {}",
            board,
        );
    }

    #[test]
    fn castle_moves_the_rook_opponent_east() {
        let mut board = board();
        board.set_by_idx(4, ins_black(Piece::King));
        board.set_by_idx(7, ins_black(Piece::Rook));

        board.do_move(&(4, 6));

        assert_eq!(
            board.get(&Square::A7).as_ref(),
            None,
            "rook was not removed {}",
            board,
        );

        assert_eq!(
            board.get(&Square::F8).as_ref(),
            ins_black(Piece::Rook).as_ref(),
            "rook was not moved {}",
            board
        );
    }

    #[test]
    fn castle_only_moves_the_correct_rook_west() {
        let mut board = board_castle_you_west();
        board.set_by_idx(63, ins_white(Piece::Rook));

        board.do_move(&(60, 58));

        assert_eq!(
            board.get(&Square::H1).as_ref(),
            ins_white(Piece::Rook).as_ref(),
            "east rook was moved {}",
            board,
        );
    }

    #[test]
    fn castle_only_moves_the_correct_rook_east() {
        let mut board = board_castle_you_east();
        board.set_by_idx(56, ins_white(Piece::Rook));

        board.do_move(&(60, 62));

        assert_eq!(
            board.get(&Square::A1).as_ref(),
            ins_white(Piece::Rook).as_ref(),
            "west rook was moved {}",
            board,
        );
    }

    #[test]
    fn castle_does_not_happen_on_normal_king_moves() {
        let mut board = board();
        board.set_by_idx(56, ins_white(Piece::Rook));
        board.set_by_idx(60, ins_white(Piece::King));

        board.do_move(&(60, 59));

        assert_eq!(
            board.get(&Square::A1).as_ref(),
            ins_white(Piece::Rook).as_ref(),
            "rook was removed",
        );
    }

    #[test]
    fn castle_move_is_not_done_for_other_pieces() {
        let mut board = board();
        board.set_by_idx(56, ins_white(Piece::Rook));
        board.set_by_idx(60, ins_white(Piece::Queen));

        board.do_move(&(60, 58));

        assert_eq!(
            board.get(&Square::A1).as_ref(),
            ins_white(Piece::Rook).as_ref(),
            "rook was replaced {}",
            board
        );
    }

    fn board_castle_you_west() -> Board {
        let mut board = board();
        board.set_by_idx(56, ins_white(Piece::Rook));
        board.set_by_idx(60, ins_white(Piece::King));
        board
    }

    fn board_castle_you_east() -> Board {
        let mut board = board();
        board.set_by_idx(60, ins_white(Piece::King));
        board.set_by_idx(63, ins_white(Piece::Rook));
        board
    }

    /// Note that the instance is created with `was_moved = true`.
    fn ins_black(piece: Piece) -> Option<PieceInstance> {
        ins(Color::Black, piece)
    }

    /// Note that the instance is created with `was_moved = true`.
    fn ins_white(piece: Piece) -> Option<PieceInstance> {
        ins(Color::White, piece)
    }

    /// Note that the instance is created with `was_moved = true`.
    fn ins(color: Color, piece: Piece) -> Option<PieceInstance> {
        Some(PieceInstance::new(color, piece))
    }

    fn board() -> Board {
        Board::new_empty()
    }
}
